filetype plugin indent on
syntax enable
set background=dark
colorscheme nord

let mapleader=","
" TODO: figure out a local leader
let mapleader=","
" remap old leader to old ","
nnoremap \ ,

" quick loading and sourcing of vimrc
nnoremap <leader>rce :tabedit $MYVIMRC<cr>
nnoremap <leader>rcs :source $MYVIMRC<cr>

""""""""""""""""""""""""""""""""""
" BASIC VIM SETTINGS
""""""""""""""""""""""""""""""""""
" maintain tab indent
set autoindent
" allow backspacing over all the things in insert mode
set backspace=indent,eol,start
" make searches dynamic
set incsearch
" highligh all search occurances
set hlsearch
" disable search highlight on enter
nnoremap <silent> <CR> :nohlsearch<CR><CR>
set hidden
" highlight current line
set cursorline
" vertical line at 81 columns
set colorcolumn=81
" show position in file
set ruler
" inplace autocomplete menu
set wildmenu
set completeopt=longest,menu,preview
" always show status bar and tab bar
set laststatus=2
set showtabline=2
set statusline=%<%f\ %h%m%r%{FugitiveStatusline()}%=%-14.(%l,%c%V%)\ %P
" current window is always at least 79x5
set winwidth=84
set winheight=5
set winminheight=5
" always some lines above and below the cursor
set scrolloff=3
" disable linewrap
set nowrap
" show line numbers relative to current line
set number
set relativenumber
" show whitespace characters
set listchars=eol:¬,tab:>\ ,trail:~,extends:>,precedes:<
" show byte count in visual mode
set showcmd

set list
nnoremap <leader>lc :set list!<cr>
"
" edit file in same directory as current file
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>

" easily switch tabs
nnoremap <leader>tn :tabnext<cr>
nnoremap <leader>tp :tabprevious<cr>

" enable spell-checker
nnoremap <silent> <leader>sp :set spell!<CR>

" unmap directional arrows
map <left> <nop>
map <right> <nop>
map <up> <nop>
map <down> <nop>

" Upper-case current work in insert mode
imap <c-u> <esc>muviwU`ua

nmap <leader>f :GFiles
nmap <leader><leader>f :Files

let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

nnoremap <expr><C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
nnoremap <expr><C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
inoremap <expr><C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<Right>"
inoremap <expr><C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<Left>"
" LOAD PLATFORM-SPECIFIC VIMRC

if filereadable(expand("~/.platform_vimrc"))
	source ~/.platform_vimrc
endif

"	open files in current directory
"	setup language environments for:
"	- c/c++
"	- rust
"	- haskell?
"	- lisp (or use emacs like a normal person?)
